/**
 * Created by Durzo on 5/25/2016.
 */

export default {
    CUSTOM_TEMPLATE_NAME_CHANGED: "CUSTOM_TEMPLATE_NAME_CHANGED",
    CUSTOM_TEMPLATE_DESCRIPTION_CHANGED: "CUSTOM_TEMPLATE_DESCRIPTION_CHANGED",
    CUSTOM_TEMPLATE_TOP_MODULES: "CUSTOM_TEMPLATE_TOP_MODULES",
    CUSTOM_TEMPLATE_ADD_MODULE: "CUSTOM_TEMPLATE_ADD_MODULE",
    CUSTOM_TEMPLATE_REMOVE_MODULE: "CUSTOM_TEMPLATE_REMOVE_MODULE",
    CUSTOM_TEMPLATE_NPM_SEARCH_SUCCESS: "CUSTOM_TEMPLATE_NPM_SEARCH_SUCCESS",
    CUSTOM_TEMPLATE_ADD_COLLABORATOR: "CUSTOM_TEMPLATE_ADD_COLLABORATOR"
}